name: Go CI

on:
  workflow_call:
    inputs:
      go-version:
        description: "Go version"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      debug: ${{ steps.debug.outputs.debug }}
    steps:
      - name: Set debug output
        id: debug
        run: |
          if [[ "${{ runner.debug }}" == "true" ]]; then
            echo "debug=true" >> $GITHUB_ENV
          else
            echo "debug=false" >> $GITHUB_ENV
          fi

  lint:
    needs: [setup]
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          args: --timeout 10m
          version: v1.59
          skip-pkg-cache: true
          skip-build-cache: true

  go_mod_tidy_check:
    needs: [setup]
    name: Go Mod Tidy Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go-version }}

      - run: go mod tidy

      - name: check for diff
        run: git diff --exit-code
